// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "lamp.h"

/////////////////////////////////////////////////////////////////////////////
// CLamp

IMPLEMENT_DYNCREATE(CLamp, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLamp properties

OLE_COLOR CLamp::GetBackColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_BACKCOLOR, VT_I4, (void*)&result);
	return result;
}

void CLamp::SetBackColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_BACKCOLOR, VT_I4, propVal);
}

OLE_COLOR CLamp::GetForeColor()
{
	OLE_COLOR result;
	GetProperty(DISPID_FORECOLOR, VT_I4, (void*)&result);
	return result;
}

void CLamp::SetForeColor(OLE_COLOR propVal)
{
	SetProperty(DISPID_FORECOLOR, VT_I4, propVal);
}

BOOL CLamp::GetEnabled()
{
	BOOL result;
	GetProperty(DISPID_ENABLED, VT_BOOL, (void*)&result);
	return result;
}

void CLamp::SetEnabled(BOOL propVal)
{
	SetProperty(DISPID_ENABLED, VT_BOOL, propVal);
}

BOOL CLamp::GetRound()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CLamp::SetRound(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

long CLamp::GetRgby()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CLamp::SetRgby(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

BOOL CLamp::GetDisplayBmp()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CLamp::SetDisplayBmp(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

long CLamp::GetRoundAngle()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CLamp::SetRoundAngle(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

long CLamp::GetRoundRect()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CLamp::SetRoundRect(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CLamp operations

void CLamp::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
