#if !defined(AFX_LAMP1_H__84CB56A1_43AF_44DA_AE78_C41D3E3155A0__INCLUDED_)
#define AFX_LAMP1_H__84CB56A1_43AF_44DA_AE78_C41D3E3155A0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLamp wrapper class

class CLamp : public CWnd
{
protected:
	DECLARE_DYNCREATE(CLamp)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9da7072b, 0xa6db, 0x4819, { 0x8f, 0xdc, 0xc8, 0x18, 0xcc, 0x82, 0xa0, 0x2d } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	BOOL GetRound();
	void SetRound(BOOL);
	long GetRgby();
	void SetRgby(long);
	BOOL GetDisplayBmp();
	void SetDisplayBmp(BOOL);
	long GetRoundAngle();
	void SetRoundAngle(long);
	long GetRoundRect();
	void SetRoundRect(long);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LAMP1_H__84CB56A1_43AF_44DA_AE78_C41D3E3155A0__INCLUDED_)
