#if !defined(AFX_PLANINFO_H__6F61CDD2_2856_41B8_BED3_A4992E06208B__INCLUDED_)
#define AFX_PLANINFO_H__6F61CDD2_2856_41B8_BED3_A4992E06208B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CPlanInfo wrapper class

class CPlanInfo : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPlanInfo)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x769d5aae, 0x342, 0x424f, { 0x9a, 0xbd, 0x38, 0x6e, 0x44, 0xba, 0x41, 0x23 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	CString GetCaption();
	void SetCaption(LPCTSTR);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	long GetAlign();
	void SetAlign(long);
	float GetMax();
	void SetMax(float);
	float GetMin();
	void SetMin(float);
	float GetValue();
	void SetValue(float);
	unsigned long GetTextColor();
	void SetTextColor(unsigned long);
	unsigned long GetScaleColor();
	void SetScaleColor(unsigned long);
	float GetPlanValue();
	void SetPlanValue(float);
	unsigned long GetPlanColor();
	void SetPlanColor(unsigned long);
	BOOL GetBorder();
	void SetBorder(BOOL);
	BOOL GetDisplayCaption();
	void SetDisplayCaption(BOOL);
	short GetDegree();
	void SetDegree(short);
	BOOL GetDisplayScale();
	void SetDisplayScale(BOOL);

// Operations
public:
	float GetClickIndex();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PLANINFO_H__6F61CDD2_2856_41B8_BED3_A4992E06208B__INCLUDED_)
