//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BallCut.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BALLCUT_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_BK                   159
#define IDD_DIALOG_KEYNUMBER            162
#define IDD_DIALOG_KEYCHAR              163
#define IDB_BITMAP_CLOSE2               167
#define IDB_BITMAP_CLOSE1               168
#define IDB_BITMAP_AUTO1                169
#define IDB_BITMAP_AUTO2                170
#define IDB_BITMAP_HAND2                171
#define IDB_BITMAP_ZERO2                172
#define IDB_BITMAP_ZERO1                173
#define IDB_BITMAP_HAND1                174
#define IDB_BITMAP_WORKPARAM2           175
#define IDB_BITMAP_EXAMINE1             176
#define IDB_BITMAP_XEAMINE2             177
#define IDB_BITMAP_EXAMINE2             177
#define IDB_BITMAP_WORKPARAM1           178
#define IDD_DLG_EXAMINE                 179
#define IDD_DLG_HAND                    180
#define IDD_DLG_WORK_PARAM              182
#define IDD_DLG_ZERO                    183
#define IDB_BITMAP_HAND3                185
#define IDB_BITMAP_ZERO3                186
#define IDB_BITMAP_AUTO3                187
#define IDB_BITMAP_HOMES2               188
#define IDB_BITMAP_HOMES1               189
#define IDB_BITMAP_HOMES3               190
#define IDB_BITMAP_POWERLAND            191
#define IDB_BITMAP_HANDAUX2             192
#define IDB_BITMAP_HANDAUX1             193
#define IDB_BITMAP_HOME_STOP2           195
#define IDB_BITMAP_HOME_STOP1           196
#define IDB_BITMAP_HOME2                197
#define IDB_BITMAP_HOME1                198
#define IDB_BITMAP_HOMEM2               199
#define IDB_BITMAP_HOMEM1               200
#define IDB_BITMAP_HOMEM3               201
#define IDC_CURSOR1                     204
#define IDB_BITMAP_CUT_STOP2            207
#define IDB_BITMAP_CUT_STOP1            208
#define IDB_BITMAP_CUT_SUSPEND1         209
#define IDB_BITMAP_CUT_SUSPEND2         210
#define IDB_BITMAP_CUT_TEST2            211
#define IDB_BITMAP_TESTING2             211
#define IDB_BITMAP_CUT_TEST1            212
#define IDB_BITMAP_TESTING1             212
#define IDB_BITMAP_CUT_BEGAN2           213
#define IDB_BITMAP_CUT_BEGAN1           214
#define IDB_BITMAP_DIALOG               216
#define IDD_DIALOG_MACHINE_PARAM        218
#define IDB_BITMAP_BACK1                220
#define IDB_BITMAP_ALAM2                221
#define IDB_BITMAP_ALAM1                222
#define IDB_BITMAP_MACHINE_PARAM1       223
#define IDB_BITMAP_MACHINE_PARAM2       224
#define IDB_BITMAP_BACK2                225
#define IDB_BITMAP_SAVE1                226
#define IDB_BITMAP_SAVE2                227
#define IDB_BITMAP_PRODUCT2             230
#define IDB_BITMAP_PRODUCT1             231
#define IDB_BITMAP_PRODUCT3             232
#define IDB_BITMAP_CUTING2              233
#define IDB_BITMAP_CUTING1              234
#define IDD_DIALOG_CAUTION_MESSAGE      235
#define IDB_BITMAP_TESTING3             236
#define IDB_BITMAP_CUTING3              237
#define IDB_BITMAP_IOPUT1               238
#define IDB_BITMAP_IOPUT2               239
#define IDC_CURSOR2                     244
#define IDD_DIALOG_ADJUST               245
#define IDB_BITMAP_ADJUST2              246
#define IDB_BITMAP_ADJUST1              247
#define IDB_BITMAP_HISTORYALARM1        249
#define IDB_BITMAP_HISTORYALARM2        250
#define IDB_BITMAP_POLE_SIDE            253
#define IDB_BITMAP_POLE_EDGE            254
#define IDB_BITMAP_POLE_CENTER          255
#define IDB_BITMAP_EQUATOR              256
#define IDB_BITMAP_CUT_SUSPEND3         257
#define IDD_DIALOG_SHOW_FIRE_CUT_POS    258
#define IDD_DLG_THREE_BALL              260
#define IDD_DLG_FOUR_BALL               262
#define IDB_BITMAP_3SIDE                269
#define IDB_BITMAP_3EQUATOR             270
#define IDB_BITMAP_3CENTER              271
#define IDB_BITMAP1                     273
#define IDB_BITMAP2                     274
#define IDB_BITMAP3                     275
#define IDC_STATIC_TITLE                317
#define IDC_CAPTIONINFOCTRL1            1002
#define IDC_BTN_HAND                    1003
#define IDC_CAPTIONINFOCTRL_TIME        1003
#define IDC_BUTTON_L                    1005
#define IDC_BTN_AUTO                    1006
#define IDC_BUTTON_R                    1006
#define IDC_BTN_ZERO                    1008
#define IDC_BTN_EXAMINE                 1009
#define IDC_BTN_WORKPARAM               1010
#define IDC_BTN_CLOSE                   1011
#define IDC_RADIO_PA                    1014
#define IDC_EDIT_PULSEX                 1015
#define IDC_RADIO_PR                    1016
#define IDC_EDIT_PULSEY                 1016
#define IDC_BTN_HOMEX                   1016
#define IDC_EDIT_PULSEZ                 1017
#define IDC_BTN_HOMEY                   1017
#define IDC_RADIO_POLE_EDGE             1018
#define IDC_EDIT_PULSEA                 1018
#define IDC_BTN_HOMEZ                   1018
#define IDC_RADIO_POLE_SIDE             1019
#define IDC_EDIT_HAND_ADDX              1019
#define IDC_BTN_HOMEA                   1019
#define IDC_EDIT_HAND_ADDY              1020
#define IDC_EDIT_PRZ                    1020
#define IDC_BTN_HOMEB                   1020
#define IDC_EDIT_HAND_ADDZ              1021
#define IDC_BTN_HOMEC                   1021
#define IDC_EDIT_HAND_ADDA              1022
#define IDC_EDIT_PRB                    1022
#define IDC_BTN_HOME_ALL                1022
#define IDC_EDIT_HAND_SUBX              1023
#define IDC_BTN_HOME_STOP               1023
#define IDC_EDIT_HAND_SUBY              1024
#define IDC_BTN_HOME_MACHINE            1024
#define IDC_EDIT_HAND_SUBZ              1025
#define IDC_BTN_HOME_SOFT               1025
#define IDC_EDIT_HAND_SUBA              1026
#define IDC_EDIT_HAND_SPEEDX            1027
#define IDC_EDIT_HAND_SPEEDY            1028
#define IDC_EDIT_HAND_SPEEDZ            1029
#define IDC_STATIC_PRX                  1030
#define IDC_EDIT_HAND_SPEEDA            1030
#define IDC_BUTTON_A                    1030
#define IDC_STATIC_PRY                  1031
#define IDC_EDIT_ZERO_SPEEDX            1031
#define IDC_BUTTON_B                    1031
#define IDC_STATIC_PRZ                  1032
#define IDC_EDIT_ZERO_SPEEDY            1032
#define IDC_STATIC_PRA                  1033
#define IDC_EDIT_ZERO_SPEEDZ            1033
#define IDC_STATIC_PRB                  1034
#define IDC_EDIT_ZERO_SPEEDA            1034
#define IDC_STATIC_PRC                  1035
#define IDC_EDIT_LIMITFX                1035
#define IDC_STATIC_SPX                  1036
#define IDC_EDIT_LIMITFY                1036
#define IDC_STATIC_SPY                  1037
#define IDC_EDIT_LIMITFZ                1037
#define IDC_STATIC_SPZ                  1038
#define IDC_EDIT_LIMITFA                1038
#define IDC_STATIC_SPA                  1039
#define IDC_EDIT_PULSEB                 1039
#define IDC_STATIC_SPB                  1040
#define IDC_EDIT_PULSEC                 1040
#define IDC_STATIC_SPC                  1041
#define IDC_EDIT_HAND_SUBB              1041
#define IDC_EDIT_HAND_SUBC              1042
#define IDC_LAMPCTRL2                   1043
#define IDC_EDIT_HAND_SPEEDB            1043
#define IDC_LAMP_STATEA                 1043
#define IDC_LAMPCTRL3                   1044
#define IDC_EDIT_HAND_SPEEDC            1044
#define IDC_LAMP_STATEB                 1044
#define IDC_LAMPCTRL4                   1045
#define IDC_EDIT_LIMITFB                1045
#define IDC_LAMP_STATEC                 1045
#define IDC_LAMPCTRL5                   1046
#define IDC_EDIT_LIMITFC                1046
#define IDC_LAMP_STATEX                 1046
#define IDC_LAMPCTRL6                   1047
#define IDC_EDIT_HAND_ADDB              1047
#define IDC_LAMP_STATEY                 1047
#define IDC_LAMPCTRL7                   1048
#define IDC_EDIT_HAND_ADDC              1048
#define IDC_LAMP_STATEZ                 1048
#define IDC_EDIT_ZERO_SPEEDB            1049
#define IDC_RADIO_CUT                   1050
#define IDC_EDIT_ZERO_SPEEDC            1050
#define IDC_RADIO_TEST                  1051
#define IDC_EDIT_LIMITRX                1051
#define IDC_RADIO_EQUATOR               1052
#define IDC_EDIT_LIMITRY                1052
#define IDC_RADIO_POLE_CENTER           1053
#define IDC_EDIT_LIMITRZ                1053
#define IDC_EDIT_LIMITRA                1054
#define IDC_EDIT_LIMITRB                1055
#define IDC_SLIDER_MULTIPLY             1056
#define IDC_EDIT_LIMITRC                1056
#define IDC_EDIT_ZORE_OFFSETX           1059
#define IDC_EDIT_ZORE_OFFSETY           1060
#define IDC_EDIT_ZORE_OFFSETZ           1061
#define IDC_EDIT_ZORE_OFFSETA           1062
#define IDC_EDIT_ZORE_OFFSETB           1063
#define IDC_EDIT_ZORE_OFFSETC           1064
#define IDC_STATIC1                     1065
#define IDC_STATIC2                     1066
#define IDC_STATIC3                     1067
#define IDC_STATIC4                     1068
#define IDC_STATIC5                     1069
#define IDC_STATIC6                     1070
#define IDC_STATIC7                     1071
#define IDC_STATIC8                     1072
#define IDC_STATIC9                     1073
#define IDC_STATIC11                    1075
#define IDC_STATIC12                    1076
#define IDC_STATIC13                    1077
#define IDC_STATIC14                    1078
#define IDC_STATIC15                    1079
#define IDC_STATIC16                    1080
#define IDC_DISPLAYCTRLCTRL_OUT1        1082
#define IDC_EDIT_4SB                    1082
#define IDC_DISPLAYCTRLCTRL_OUT2        1083
#define IDC_EDIT_4SG                    1083
#define IDC_DISPLAYCTRLCTRL_IN1         1084
#define IDC_EDIT_4SE                    1084
#define IDC_DISPLAYCTRLCTRL_IN2         1085
#define IDC_DISPLAYCTRLCTRL_IN3         1086
#define IDC_EDIT_4SGA                   1086
#define IDC_DISPLAYCTRLCTRL_IN4         1087
#define IDC_EDIT_4EDA                   1087
#define IDC_DISPLAYCTRLCTRL_IN5         1088
#define IDC_EDIT_4EB                    1088
#define IDC_EDIT_4EDB                   1088
#define IDC_DISPLAYCTRLCTRL_IN6         1089
#define IDC_EDIT_4EDG                   1089
#define IDC_EDIT_4EDAA                  1090
#define IDC_EDIT_4EDE                   1091
#define IDC_EDIT_4EDGA                  1092
#define IDC_EDIT_4CA                    1093
#define IDC_EDIT_4CG                    1094
#define IDC_EDIT_4CAA                   1095
#define IDC_EDIT_4CGA                   1096
#define IDC_EDIT_4EA                    1097
#define IDC_EDIT_4EG                    1098
#define IDC_EDIT_4EAA                   1099
#define IDC_EDIT_4EGA                   1100
#define IDC_EDIT_THICK                  1101
#define IDC_EDIT_BALL_RADIUS            1102
#define IDC_EDIT_CUT_SPEED              1103
#define IDC_EDIT_CUT_ADD                1104
#define IDC_EDIT_CUT_SUB                1105
#define IDC_EDIT_PRX                    1106
#define IDC_STATIC18                    1106
#define IDC_EDIT_BAUX_RADIUS            1106
#define IDC_EDIT_PRY                    1107
#define IDC_STATIC19                    1107
#define IDC_EDIT_OVER_CUT               1107
#define IDC_EDIT_PRA                    1108
#define IDC_STATIC20                    1108
#define IDC_EDIT_CENTER_OFFSET          1108
#define IDC_EDIT_PRC                    1109
#define IDC_STATIC21                    1109
#define IDC_EDIT_POS_400                1109
#define IDC_STATIC22                    1110
#define IDC_EDIT_POS_650                1110
#define IDC_BUTTON1                     1111
#define IDC_BTN_ADJUST_BEGAN            1111
#define IDC_STATIC23                    1111
#define IDC_BTN_ADJUST_STOP             1112
#define IDC_STATIC24                    1112
#define IDC_LIST_ALARM                  1113
#define IDC_BTN_ADJUST_SET              1113
#define IDC_STATIC25                    1113
#define IDC_EDIT_POS_3000               1113
#define IDC_STATICO                     1114
#define IDC_BTN_ADJUST_BACK             1114
#define IDC_STATIC26                    1114
#define IDC_STATICI                     1115
#define IDC_STATIC27                    1115
#define IDC_STATIC28                    1116
#define IDC_STATIC_AFX                  1120
#define IDC_STATIC_GMTPX                1123
#define IDC_STATIC_GMTPG                1124
#define IDC_CHECK_OR_TOUCH              1127
#define IDC_STATIC_COMPANY              1128
#define IDC_STATIC_POLE_SIDE            1129
#define IDC_STATIC_POLE_EDGE            1130
#define IDC_STATIC_POLE_CENTER          1131
#define IDC_STATIC_EQUATOR              1132
#define IDC_BUTTON2                     1134
#define IDC_BUTTON_1                    1137
#define IDC_BUTTON_2                    1138
#define IDC_LAMPCTRL1                   1139
#define IDC_BTN_FOUE_BALL               1140
#define IDC_BTN_THREE_BALL              1141
#define IDC_BTN_CANCLE_FOUR_BALL        1141
#define IDC_BTN_SAVE_FOUR_BALL          1142
#define IDC_BTN_SAVE_THREE_BALL         1142
#define IDC_BTN_CANCLE_THREE_BALL       1143
#define IDC_BTNCTLCTRL1                 1143
#define IDC_BTN_SET_ZORE                1143
#define IDC_EDIT_3EA                    1144
#define IDC_BTN_POS_400                 1144
#define IDC_EDIT_OLD                    1145
#define IDC_EDIT_3EB                    1145
#define IDC_STATIC_3CENTER              1145
#define IDC_EDIT_NEW                    1146
#define IDC_EDIT_3EAA                   1146
#define IDC_STATIC_3EQUTOR2             1146
#define IDC_STATIC_3EQUTOR              1146
#define IDC_STATIC_NEW                  1147
#define IDC_EDIT_3EBA                   1147
#define IDC_STATIC_3SIDE                1147
#define IDC_STATIC_OLD                  1148
#define IDC_EDIT_3CEA                   1148
#define IDC_EDIT_3CA                    1148
#define IDC_BTN_POS_650                 1148
#define IDC_BUTTON_BK                   1149
#define IDC_EDIT_3CB                    1149
#define IDC_BUTTON_DEL                  1150
#define IDC_EDIT_3CG                    1150
#define IDC_OK                          1151
#define IDC_EDIT_3CBA                   1151
#define IDC_BTN_4CENTER                 1151
#define IDC_EDIT_3SA                    1152
#define IDC_BTN_3CENTER                 1152
#define IDC_EDIT_3SB                    1153
#define IDC_BTN_3SIDE                   1153
#define IDC_EDIT_3SG                    1154
#define IDC_EDIT_3SAA                   1155
#define IDC_BTN_4SIDE                   1155
#define IDC_EDIT_3CGA                   1156
#define IDC_BTN_BACKE                   1200
#define IDC_BTN_ALAM                    1201
#define IDC_BTN_IOPUT                   1202
#define IDC_BTN_BACKM                   1202
#define IDC_BTN_HISTORYALARM            1203
#define IDC_BTN_BACKW                   1203
#define IDC_BTN_MACHINE_PARAM           1204
#define IDC_BTN_SAVEM                   1205
#define IDC_BTN_SAVEW                   1206
#define IDC_BTN_CUT_SUSPEND             1209
#define IDC_BTN_CUT_BEGAN               1210
#define IDC_BTN_CUT_STOP                1211
#define IDC_BTN_EQUTOR                  1212
#define IDC_BTN_POLE_CENTER             1213
#define IDC_BTN_3EQUTOR                 1213
#define IDC_BTN_POLE_EDGE               1214
#define IDC_BTN_POLE_SIDE               1215
#define IDC_BTN_HANDXF                  1216
#define IDC_BTN_HANDXR                  1217
#define IDC_BTN_HANDYF                  1218
#define IDC_BTN_HANDYR                  1219
#define IDC_BTN_HANDZF                  1220
#define IDC_BTN_HANDZR                  1221
#define IDC_BTN_HANDAF                  1222
#define IDC_BTN_HANDAR                  1223
#define IDC_BTN_HANDBF                  1224
#define IDC_BUTTON_3                    1224
#define IDC_BTN_HANDBR                  1225
#define IDC_BUTTON_4                    1225
#define IDC_BTN_HANDCF                  1226
#define IDC_BUTTON_5                    1226
#define IDC_BTN_HANDCR                  1227
#define IDC_BUTTON_6                    1227
#define IDC_BTN_HAND_MOTION_STYLE       1228
#define IDC_BUTTON_7                    1228
#define IDC_BTN_HAND_BAGEN              1229
#define IDC_BUTTON_8                    1229
#define IDC_BTN_HAND_STOP               1230
#define IDC_BUTTON_9                    1230
#define IDC_BUTTON_0                    1231
#define IDC_BUTTON_BACKSPACE            1232
#define IDC_BUTTON_Q                    1233
#define IDC_BUTTON_E                    1235
#define IDC_BUTTON_T                    1237
#define IDC_BUTTON_U                    1239
#define IDC_BUTTON_I                    1240
#define IDC_BUTTON_O                    1241
#define IDC_BUTTON_P                    1242
#define IDC_BUTTON_DIRECTORY            1243
#define IDC_BUTTON_S                    1245
#define IDC_BUTTON_D                    1246
#define IDC_BUTTON_F                    1247
#define IDC_BUTTON_H                    1249
#define IDC_BUTTON_J                    1250
#define IDC_BUTTON_K                    1251
#define IDC_BUTTON_QUOTATIONMARK        1252
#define IDC_BUTTON_ENTER                1253
#define IDC_BUTTON_SHIFTL               1254
#define IDC_BUTTON_C                    1257
#define IDC_BUTTON_V                    1258
#define IDC_BUTTON_N                    1260
#define IDC_BUTTON_M                    1261
#define IDC_BUTTON_COMMA                1262
#define IDC_BUTTON_SHIFTR               1263
#define IDC_BUTTON_SUB                  1264
#define IDC_BUTTON_EQUATION             1265
#define IDC_BUTTON_INCLUDEL             1266
#define IDC_BUTTON_INCLUDER             1267
#define IDC_BUTTON_SEMICOLON            1269
#define IDC_BUTTON_POINT                1270
#define IDC_BUTTON_DIVIDE               1271
#define IDC_BUTTON_G                    1290
#define IDC_BUTTON11                    1303
#define IDC_BUTTON12                    1304
#define IDC_BUTTON13                    1305
#define IDC_BUTTON_X                    1308
#define IDC_BUTTON_Y                    1309
#define IDC_BUTTON_Z                    1310
#define IDC_BUTTON_W                    1331
#define IDC_STATIC17                    1481
#define IDC_BTN_HOT_GAS                 1501
#define IDC_BTN_FIRE_GAS                1502
#define IDC_BTN_CUT_GAS                 1503
#define IDC_BTN_RELEASE_GAS             1504

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        276
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1146
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
